//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinkGeo.MapSuite.GisEditor.Plugins.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GoogleEarthResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GoogleEarthResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThinkGeo.MapSuite.GisEditor.Plugins.Properties.GoogleEarthResources", typeof(GoogleEarthResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were unable to close the polygon. Please check to make sure your polygon is formed correctly and it has a point of beginning.
        /// </summary>
        internal static string CanNotAutoClose {
            get {
                return ResourceManager.GetString("CanNotAutoClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were unable to generate a correct polygon. Please check to make sure your polygon is formed correctly and it has a point of beginning..
        /// </summary>
        internal static string CanNotSaveToFile {
            get {
                return ResourceManager.GetString("CanNotSaveToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing the call type will cause us to update the call list to use the new direction type.  Would you like to continue?.
        /// </summary>
        internal static string ChangeDirectionTypeWarning {
            get {
                return ResourceManager.GetString("ChangeDirectionTypeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing the direction unit will cause us to update the call list to use the new direction unit.  Would you like to continue?.
        /// </summary>
        internal static string ChangeDirectionUnitWarning {
            get {
                return ResourceManager.GetString("ChangeDirectionUnitWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current polygon shape is already closed..
        /// </summary>
        internal static string DoNotNeedClose {
            get {
                return ResourceManager.GetString("DoNotNeedClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set the ListView property during a drag operation..
        /// </summary>
        internal static string DragIsInProgress {
            get {
                return ResourceManager.GetString("DragIsInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A point of beginning already exists, do you want to replace it?.
        /// </summary>
        internal static string HasStartPoint {
            get {
                return ResourceManager.GetString("HasStartPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A point of beginning already exists..
        /// </summary>
        internal static string HasStartPointWarning {
            get {
                return ResourceManager.GetString("HasStartPointWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied to clipboard successfully..
        /// </summary>
        internal static string ImageCopySucceed {
            get {
                return ResourceManager.GetString("ImageCopySucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not open the file for none Google Earth executable file (googleearth.exe), did you want to save the file?.
        /// </summary>
        internal static string NoneGoogleEarthExecutableFile {
            get {
                return ResourceManager.GetString("NoneGoogleEarthExecutableFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None Google Earth executable file.
        /// </summary>
        internal static string NoneGoogleEarthExecutableFileCaption {
            get {
                return ResourceManager.GetString("NoneGoogleEarthExecutableFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Google Earth&quot; is not insatlled on local machine, please download at &quot;http://www.google.com/earth/download/ge/agree.html&quot;, do you want to save the file?.
        /// </summary>
        internal static string NoneGoogleEarthInstalled {
            get {
                return ResourceManager.GetString("NoneGoogleEarthInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None Google Earth installed.
        /// </summary>
        internal static string NoneGoogleEarthInstalledCaption {
            get {
                return ResourceManager.GetString("NoneGoogleEarthInstalledCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to close the dialog?.
        /// </summary>
        internal static string QuitMessage {
            get {
                return ResourceManager.GetString("QuitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changes haven&apos;t been saved, please click &quot;Yes&quot; to save it or &quot;No&quot; to discard the changes..
        /// </summary>
        internal static string QuitSaveMessage {
            get {
                return ResourceManager.GetString("QuitSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input value must be numeric..
        /// </summary>
        internal static string ShouldBeDouble {
            get {
                return ResourceManager.GetString("ShouldBeDouble", resourceCulture);
            }
        }
    }
}
