//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinkGeo.MapSuite.WpfDesktop.Extension.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThinkGeo.MapSuite.WpfDesktop.Extension.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.ObjectModel;
        ///using System.Collections.Generic;
        ///using ThinkGeo.MapSuite.Core;
        ///using System;
        ///
        ///public class Script   
        ///{
        ///  public static Collection&lt;Feature&gt; GetFeaturesToMatch(IEnumerable&lt;Feature&gt; features)
        ///  {
        ///       Collection&lt;Feature&gt; newFeatures = new Collection&lt;Feature&gt;();	   
        ///       foreach(var feature in features) {
        ///         if(Match(feature)) newFeatures.Add(feature);
        ///       }
        ///	   
        ///	   return newFeatures;
        ///  }
        ///  
        ///  private static bool Match(Feature f)
        ///  {
        ///     return [expression] [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CSharpFilterCondition {
            get {
                return ResourceManager.GetString("CSharpFilterCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.ObjectModel;
        ///using System.Collections.Generic;
        ///using ThinkGeo.MapSuite.Core;
        ///using System;
        ///
        ///public class Script   
        ///{
        ///  public static Collection&lt;Feature&gt; GetFeaturesToMatch(IEnumerable&lt;Feature&gt; features)
        ///  {
        ///       Collection&lt;Feature&gt; newFeatures  = new Collection&lt;Feature&gt;();
        ///	   
        ///       foreach(var feature in features) {
        ///         if(Match(feature)) newFeatures.Add(feature);
        ///       }
        ///	   
        ///	   return newFeatures;
        ///  }
        ///  
        ///  private static bool Match(Feature feature)
        ///  {
        ///       [expressi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CSharpFilterFunction {
            get {
                return ResourceManager.GetString("CSharpFilterFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //The code below shows how to write C# Script for MapSuite Explorer
        /////You can use &quot;map&quot; to access the WpfMap control
        ///using System;
        ///using System.Windows.Forms;
        ///using ThinkGeo.MapSuite.WpfDesktopEdition;
        ///
        ///public class Script
        ///{
        ///    public static void ScriptMain(WpfMap map)
        ///    {
        ///        int count = 0;
        ///
        ///        Timer timer = new Timer();
        ///        timer.Interval = 600;
        ///        timer.Tick += (object sender, EventArgs e) =&gt;
        ///        {
        ///            count++;
        ///            if (count == 12)
        ///            {
        ///                ti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CSharpSampleCode {
            get {
                return ResourceManager.GetString("CSharpSampleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some invalid features exist in current shape files, we have ignored them and click OK to continue..
        /// </summary>
        internal static string InvalidFeatures {
            get {
                return ResourceManager.GetString("InvalidFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import clr
        ///clr.AddReference(&quot;mscorlib&quot;)
        ///clr.AddReference(&quot;MapSuiteCore&quot;)
        ///
        ///from System.Collections.ObjectModel import *
        ///from ThinkGeo.MapSuite.Core import *
        ///
        ///def matchFeature(f):
        ///	return [expression]
        ///
        ///features = Collection[Feature]()
        ///for f in Features:
        ///	try:
        ///		if matchFeature(f): features.Add(f)
        ///	except:
        ///		pass
        ///features.
        /// </summary>
        internal static string PythonFilterCondition {
            get {
                return ResourceManager.GetString("PythonFilterCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import clr
        ///clr.AddReference(&quot;mscorlib&quot;)
        ///clr.AddReference(&quot;MapSuiteCore&quot;)
        ///
        ///from System.Collections.ObjectModel import *
        ///from ThinkGeo.MapSuite.Core import *
        ///def match(feature):
        ///[expression]
        ///
        ///features = Collection[Feature]()
        ///for f in Features:
        ///	try:
        ///		if match(f): features.Add(f)
        ///	except:
        ///		pass
        ///features.
        /// </summary>
        internal static string PythonFilterFunction {
            get {
                return ResourceManager.GetString("PythonFilterFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #The code below shows how to write Python Script for MapSuite Explorer
        ///#You can use &quot;Map&quot; to access the WpfMap control
        ///import clr
        ///clr.AddReference(&apos;System.Windows.Forms&apos;)
        ///from System.Windows.Forms import *
        ///
        ///count=0
        ///
        ///def timer_Tick(*args):
        ///	global count
        ///	count+=1
        ///	if count==12:
        ///		timer.Stop()
        ///		
        ///	if count%2==0:
        ///		Map.ZoomIn()
        ///	else:
        ///		Map.ZoomOut()
        ///
        ///timer=Timer()
        ///timer.Tick+=timer_Tick
        ///timer.Interval=600
        ///timer.Start().
        /// </summary>
        internal static string PythonSampleCode {
            get {
                return ResourceManager.GetString("PythonSampleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to load_assembly(&quot;mscorlib&quot;)
        ///load_assembly(&quot;MapSuiteCore&quot;)
        ///
        ///def isMatch(f)                                                                                                                                             var =  ([expression])
        ///        return var
        ///end
        ///
        ///def getMatchFeatures(featuresToMatch)
        ///	matchFeatures = System::Collections::ObjectModel::Collection[ThinkGeo::MapSuite::Core::Feature].new
        ///	featuresToMatch.each do |f|
        ///		begin
        ///			if isMatch(f)
        ///				matchFeatures&lt;&lt;f
        ///			end
        ///		rescue
        ///
        ///		end
        ///	end
        ///	return matc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RubyFilterCondition {
            get {
                return ResourceManager.GetString("RubyFilterCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to load_assembly(&quot;mscorlib&quot;)
        ///load_assembly(&quot;MapSuiteCore&quot;)
        ///                                                                                                                                                              def match(feature)  
        ///    [expression]
        /// end                                                                                                                                                              
        ///def getMatchFeatures(featuresToMatch)
        ///	matchFeatures = System::Collections::ObjectModel::Collecti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RubyFilterFunction {
            get {
                return ResourceManager.GetString("RubyFilterFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #The code below shows how to write Ruby Script for MapSuite Explorer
        ///#You can use &quot;Map&quot; to access the WpfMap control
        ///
        ///load_assembly(&quot;System.Windows.Forms&quot;)
        ///
        ///count=0
        ///
        ///timer=System::Windows::Forms::Timer.new
        ///timer.Interval=600
        ///
        ///timer.Tick do |sender,e|
        ///	count+=1
        ///	if count==12
        ///		timer.Stop
        ///	end
        ///	
        ///	if count%2==0
        ///		Map.ZoomIn
        ///	else
        ///		Map.ZoomOut
        ///	end
        ///end
        ///
        ///timer.Start.
        /// </summary>
        internal static string RubySampleCode {
            get {
                return ResourceManager.GetString("RubySampleCode", resourceCulture);
            }
        }
    }
}
