<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>GalaSoft.MvvmLight.WPF4</AssemblyName>
    <RootNamespace>GalaSoft.MvvmLight</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Windows.Interactivity.WPF" Version="2.0.20525" />
  </ItemGroup>
</Project>
